# Generated by Django 4.0.5 on 2022-07-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=50)),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.birthday')),
            ],
        ),
    ]
