# Generated by Django 4.0.5 on 2022-07-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='name',
            new_name='giftName',
        ),
    ]
