# Generated by Django 4.0.5 on 2022-07-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_name_gift_giftname'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='relationship',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
