# Generated by Django 4.0.5 on 2022-07-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_birthday_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='recipient',
        ),
    ]
