# Generated by Django 4.0.6 on 2022-07-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_remove_gift_birthday_birthday_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
