# Generated by Django 4.0.6 on 2022-07-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_birthday_user_gift_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='giftName',
            new_name='name',
        ),
    ]
